Repository roses16-dev/week-3-board, pull requests merged in 2022-10, with the labels that each got.

#1 Error / getPost PostDetail에서 발생하는 TypeError fix
  src/components/postdetail/PostDetail.jsx
  src/pages/Detail.jsx
  src/redux/modules/postsSlice.js
Labels: bug

#2 feature / 글쓰기 기능 추가
  package.json
  src/components/postwrite/PostWrite.jsx
  src/components/postwrite/styled.jsx
  src/pages/Write.jsx
  src/redux/modules/postsSlice.js
  yarn.lock
Labels: enhancement

#4 error/#3 PostDetail 버튼 반응없음
  db.json
  src/components/postdetail/PostDetail.jsx
Labels: bug

#6 feature/수정하기 기능 추가
  src/components/postdetail/PostDetail.jsx
  src/components/postwrite/PostWrite.jsx
  src/pages/List.jsx
  src/pages/Write.jsx
  src/shared/Router.js
Labels: enhancement

#9 test
  src/components/header/Header.jsx
Labels: bug, documentation, duplicate, enhancement, help wanted, good first issue, invalid, question

#10 댓글조회하기 버그수정
  db.json
  src/pages/Detail.jsx
  src/redux/config/configStore.js
Labels: bug

#11 feature/List infinite scroll 추가
  db.json
  package.json
  src/hooks/useInfiniteScroll.js
  src/pages/List.jsx
  src/redux/modules/postsSlice.js
  yarn.lock
Labels: enhancement

#15 댓글추가기능추가
  db.json
  src/App.css
  src/App.js
  src/components/postdetail/Comment.jsx
  src/components/postdetail/comment.css
  src/redux/modules/commentSlice.js
Labels: documentation

#18 error/#17 코멘트 전체삭제 오류 수정 완료
  db.json
  src/components/postdetail/Comment.jsx
  src/redux/modules/commentSlice.js
Labels: bug

#19 feature/Newbutton 컴포넌트 추가 및 관련 컴포넌트 버튼 수정
  src/components/header/Header.jsx
  src/components/newbutton/NewButton.jsx
  src/components/postdetail/PostDetail.jsx
  src/components/postsummary/PostSummary.jsx
  src/components/postsummary/style.jsx
  src/components/postwrite/PostWrite.jsx
Labels: enhancement

#21 1
  db.json
  src/components/newbutton/NewButton.jsx
  src/components/postdetail/Comment.jsx
  src/components/postdetail/comment.css
  src/components/postwrite/PostWrite.jsx
Labels: bug, enhancement

#24 Seongwoo
  db.json
  src/components/header/Header.jsx
  src/components/newbutton/NewButton.jsx
  src/components/postdetail/Comment.jsx
  src/components/postdetail/PostDetail.jsx
  src/components/postdetail/style.css
  src/components/postsummary/PostSummary.jsx
  src/components/postsummary/style.css
  src/components/postsummary/style.jsx
  src/components/postwrite/PostWrite.jsx
  src/pages/List.jsx
Labels: enhancement

#25 Seongwoo
  db.json
  src/components/postdetail/Comment.jsx
  src/components/postdetail/PostDetail.jsx
Labels: bug, question

#27 error/CSS 파일분리 후 컨텐츠 개행문자 인식불가 오류 수정
  src/components/postdetail/style.css
Labels: bug

#29 버튼컴포넌트 모든버튼에 적용함, 버튼선추가
  package.json
  src/components/newbutton/NewButton.jsx
  src/components/postdetail/Comment.jsx
  src/components/postdetail/PostDetail.jsx
  src/components/postdetail/style.css
  src/components/postsummary/PostSummary.jsx
  src/components/postsummary/style.css
  src/pages/List.jsx
  src/shared/Router.js
  yarn.lock
Labels: enhancement

#31 커밋취소테스트22
  src/components/newbutton/NewButton.jsx
Labels: bug

#32 feature / 조회수 카운트 추가
  src/components/postdetail/PostDetail.jsx
  src/components/postsummary/PostSummary.jsx
  src/components/postwrite/PostWrite.jsx
  src/components/postwrite/style.jsx
Labels: enhancement

#42 comment props 못받아오는 버그, posrtSummary 네비게이트경로 수정
  src/components/postdetail/Comment.jsx
  src/components/postsummary/PostSummary.jsx
Labels: bug
